- set_fact:
    jdk_package_name: jdk-{{ java.version }}-{{ java.platform }}.rpm
  tags: 
    - java 
    - java_installation

- name: check java package
  stat: path={{ package_download_path }}/{{ jdk_package_name }}
  register: jdk_package_exists
  tags:
    - java 
    - java_installation

- name: download jdk package if not downloaded
  get_url: 
    url={{ java.download_mirror }}/{{ java.version }}-{{ java.build }}/{{ java.oracle_java_hash }}/{{ jdk_package_name }} dest={{ package_download_path }} headers={{ java.download_cookies }}
    validate_certs={{ java.oracle_java_rpm_validate_certs }}
    timeout={{ java.oracle_java_download_timeout }}
  when: not jdk_package_exists.stat.exists 
  tags: 
    - java 
    - java_installation

- name: install jdk rpm
  yum: name={{ package_download_path }}/{{ jdk_package_name }} state=installed
  tags: 
    - java 
    - java_installation

- name: delete package downloaded if needed
  file: path={{ package_download_path }}/{{ jdk_package_name }} state=absent
  when: force_cleanup is defined and force_cleanup == "True"
  tags:
    - java 
    - java_installation

#- name: symlink to /usr/local
#  file: state=link src={{ java.installation_path }} dest=/usr/java owner=root group=root
#  tags: 
#    - java 
#    - java_installation

- name: make java system alternative
  # priority parameter its supported in Ansible > 2.2
  alternatives: name=java path={{ java.installation_path }}/bin/java link=/usr/bin/java
  tags: 
    - java 
    - java_installation
