---   
 
- name: Set program variable to 'hiveserver2'
  set_fact: program="hiveserver2"
  
- name: Deploy init.d service for hive-server2
  template: src=hive-server2.j2 dest=/etc/init.d/hive-server2 owner=root group=root mode=0755
  when: ansible_service_mgr != "systemd"

- name: Deploy systemd service for hive-server2
  template: src=hive.server2.j2 dest=/lib/systemd/system/hive-server2.service owner=root group=root mode=0644
  register: hive-server2_systemd_unit_altered
  when: ansible_service_mgr == "systemd"
  
 # daemon-reload cannot be sent to handler because it is needed before the end of play
# also, we cannot use flush_handlers before the end of play, because we have other handlers
- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  when: ansible_service_mgr == "systemd" and ( hive-server2_systemd_unit_altered.changed )
  tags:
    - skip_ansible_lint

- name: Register hive-server2 service
  service: name=hive-server2 enabled=yes