- name: start elasticsearch
  service: name=elasticsearch state=started enabled=yes

- name: stop elasticsearch
  service: name=elasticsearch state=stopped enabled=yes

- name: restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes
