---    
- name: Set program variable to 'thrift2'
  set_fact: program="{% if HBASE_THRIFT_VERSION  == '2' %}thrift2{% else %}thrift{% endif %}"
  
- debug: var=program

- name: Deploy init.d service for hbase_thrift
  template: src=hbase-master-service.j2 dest=/etc/init.d/hbase-thrift owner=root group=root mode=0755
  when: ansible_service_mgr != "systemd"

- name: Deploy systemd service for hbase_thrift
  template: src=hbase-master.service.j2 dest=/lib/systemd/system/hbase-thrift.service owner=root group=root mode=0644
  register: hbase_thrift_systemd_unit_altered
  when: ansible_service_mgr == "systemd"
  
 # daemon-reload cannot be sent to handler because it is needed before the end of play
# also, we cannot use flush_handlers before the end of play, because we have other handlers
- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  when: ansible_service_mgr == "systemd" and ( hbase_thrift_systemd_unit_altered.changed )
  tags:
    - skip_ansible_lint
 
- name: Register hbase_thrift service
  service: name=hbase-thrift enabled=yes