---   
 
- name: Set program variable to 'master'
  set_fact: program="{% if inventory_hostname in hbase_backupmaster %}'master --backup'{% else %}master{% endif %}"
  
- name: Deploy init.d service for hbase-master
  template: src=hbase-master-service.j2 dest=/etc/init.d/hbase-master owner=root group=root mode=0755
  when: ansible_service_mgr != "systemd"

- name: Deploy systemd service for hbase-master
  template: src=hbase-master.service.j2 dest=/lib/systemd/system/hbase-master.service owner=root group=root mode=0644
  register: hbase_master_systemd_unit_altered
  when: ansible_service_mgr == "systemd"
  
 # daemon-reload cannot be sent to handler because it is needed before the end of play
# also, we cannot use flush_handlers before the end of play, because we have other handlers
- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  when: ansible_service_mgr == "systemd" and ( hbase_master_systemd_unit_altered.changed )
  tags:
    - skip_ansible_lint

- name: Register hbase-master service
  service: name=hbase-master enabled=yes