---    
- name: Set program variable to 'regionserver'
  set_fact: program="regionserver"

- name: Deploy init.d service for hbase_regionserver
  template: src=hbase-master-service.j2 dest=/etc/init.d/hbase-regionserver owner=root group=root mode=0755
  when: ansible_service_mgr != "systemd"

- name: Deploy systemd service for hbase_regionserver
  template: src=hbase-master.service.j2 dest=/lib/systemd/system/hbase-regionserver owner=root group=root mode=0644
  register: hbase_regionserver_systemd_unit_altered
  when: ansible_service_mgr == "systemd"
  
 # daemon-reload cannot be sent to handler because it is needed before the end of play
# also, we cannot use flush_handlers before the end of play, because we have other handlers
- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  when: ansible_service_mgr == "systemd" and ( hbase_regionserver_systemd_unit_altered.changed )
  tags:
    - skip_ansible_lint

- name: Register hbase_regionserver service
  service: name=hbase-regionserver enabled=yes
  
  
- name: test
  tags: test
  shell: echo -e "create 'ansible_test_table', 'id'\ndisable 'ansible_test_table'\n drop 'ansible_test_table'" | hbase shell
  run_once: true