- name: enable and start firewalld
  service: name=firewalld enabled=yes state=started
  tags:
    - firewall 

- name: set port policy
  firewalld: port={{ item }}/tcp permanent=true state=enabled immediate=yes
  with_items:
    - "{{ kafka.configuration.port }}"
    - "{{ zookeeper.configuration.port }}"
  tags:
    - firewall 
  notify: firewall restart
