---
- name: Create journalnode edits dir
  file: path={{ hdfs_dfs_journalnode_edits_dir }} state=directory owner={{ hdfs_user }} group={{ hdfs_group }} mode={{ hdfs_dfs_journalnode_edits_dir_perm }}

- name: Set program variable to 'journalnode'
  set_fact: program="journalnode"

- name: Deploy init.d service for journalnode
  template: src=hdfs-service.j2 dest=/etc/init.d/hdfs-journalnode owner=root group=root mode=0755
  register: journalnode_systemd_unit_altered
  when: ansible_service_mgr != "systemd"

- name: Deploy systemd service for journalnode
  template: src=hdfs.service.j2 dest=/lib/systemd/system/hdfs-journalnode.service owner=root group=root mode=0644
  when: ansible_service_mgr == "systemd"

# daemon-reload cannot be sent to handler because it is needed before the end of play
# also, we cannot use flush_handlers before the end of play, because we have other handlers
- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  when: ansible_service_mgr == "systemd" and journalnode_systemd_unit_altered.changed
  tags:
    - skip_ansible_lint

- name: Register journalnode service
  service: name=hdfs-journalnode enabled=yes
